
package formularios;

import clases.ConexionBD;
import clases.Jugador;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio Cabrera
 */
public class frmJugadorUpdate extends javax.swing.JFrame {
    String ruta = null;
    
    /**
     * Creates new form frmJugadorUpdate
     */
    ConexionBD cn = new ConexionBD(); 
    Connection con;
    Statement st;
    ResultSet rs;
    int idSeleccion =0;
    int idTipo =0;
    int uId = 0;
    
    public frmJugadorUpdate() {
        initComponents();
        mostrarComboSelecciones();
        mostrarTipoJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCamisola = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHabilidades = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbNacionalizado = new javax.swing.JComboBox<>();
        jcbPierna = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcbSeleccion = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtValorMercado = new javax.swing.JTextField();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jbtnBuscarFoto = new javax.swing.JButton();
        lblruta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnCancelar = new javax.swing.JButton();
        jbtnGuardar1 = new javax.swing.JButton();
        lblSeleccion = new javax.swing.JLabel();
        lblposicion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gestión de jugadores");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Foto:");

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugador2.png"))); // NOI18N

        jLabel7.setText("Edad:");

        jLabel8.setText("No. Camisola:");

        jLabel9.setText("Habilidades:");

        jLabel10.setText("Pierna Habil:");

        jLabel11.setText("Nacionalizado:");

        jcbNacionalizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jcbPierna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Derecho", "Izquirda", "Ambidiestro" }));

        jLabel12.setText("Selección:");

        jcbSeleccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSeleccionItemStateChanged(evt);
            }
        });
        jcbSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcbSeleccionMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcbSeleccionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcbSeleccionMouseReleased(evt);
            }
        });
        jcbSeleccion.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jcbSeleccionInputMethodTextChanged(evt);
            }
        });
        jcbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionActionPerformed(evt);
            }
        });

        jLabel14.setText("Marca de patrocinador:");

        jLabel15.setText("Valor en el mercado:");

        jcbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoItemStateChanged(evt);
            }
        });
        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });
        jcbTipo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcbTipoPropertyChange(evt);
            }
        });

        jLabel17.setText("Posición:");

        jbtnBuscarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/searchMini.png"))); // NOI18N
        jbtnBuscarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarFotoActionPerformed(evt);
            }
        });

        lblruta.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        lblruta.setText("Ruta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(txtCamisola, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApellidos)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHabilidades))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBuscarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jcbPierna, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbNacionalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSeleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorMercado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblruta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCamisola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jbtnBuscarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(lblruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jcbNacionalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPierna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jcbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorMercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        jLabel2.setText("ID:");

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        jbtnGuardar1.setText("Aceptar");
        jbtnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardar1ActionPerformed(evt);
            }
        });

        lblSeleccion.setText("seleccion");

        lblposicion.setText("posicion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jbtnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblposicion)
                    .addComponent(lblSeleccion))
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblposicion))
                        .addGap(10, 10, 10)
                        .addComponent(lblSeleccion)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardar1ActionPerformed
        
        //elegir seleccion
        seleccionar();
        //elige tipo de jugador/posicion
        seleccionarTipo();
        
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        int camisola =  Integer.parseInt(txtCamisola.getText());
        int edad = Integer.parseInt(txtEdad.getText());
        String habilidad = txtHabilidades.getText();
        String p_habil =  jcbPierna.getSelectedItem().toString();
        String nac = jcbNacionalizado.getSelectedItem().toString();
        String mPat = txtMarca.getText();
        int valorMerc = Integer.parseInt(txtValorMercado.getText());
        
        String img_foto = "";        
        
        Jugador j = new Jugador();
        j.setNombre(nombre);
        j.setApellidos(apellidos);
        j.setImg_foto(img_foto);
        j.setEdad(edad);
        j.setCamisola(camisola);
        j.setHabilidad(habilidad);
        j.setPierna_habil(p_habil);
        j.setNacionalizado(nac);
        j.setId_seleccion(idSeleccion);
        j.setTipo(idTipo);
        j.setPatrocinador(mPat);
        j.setValor_mercado(valorMerc);
        
        guardarJugador(nombre, apellidos, img_foto,edad,camisola,habilidad,p_habil,nac,idSeleccion, idTipo, mPat,valorMerc);
        System.out.println("Registro realizado con exito!");
        
        String query = "SELECT MAX(id_jugador) AS id_jugador FROM jugador";
        
         try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query);
        
            while (rs.next()) {
                uId = rs.getInt("id_jugador");
            }
            //System.out.println(uId);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        ConexionBD conn = new ConexionBD();
       
        String url = lblruta.getText();
        if(url.trim().length() != 0 && nombre.trim().length() != 0){
            conn.guardarFotoJugador(ruta,uId);
            System.out.println("La foto se guardó exitosamente");
        }
        else{
            JOptionPane.showMessageDialog(null, "No debe dejar los campos vacios: Nombre e Imagen");
        }
        
        limpiarJtext();
       
    }//GEN-LAST:event_jbtnGuardar1ActionPerformed

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        
    }//GEN-LAST:event_jcbTipoActionPerformed

    private void jcbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoItemStateChanged

    private void jcbTipoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcbTipoPropertyChange
        
    }//GEN-LAST:event_jcbTipoPropertyChange

    private void jcbSeleccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSeleccionItemStateChanged
        
    }//GEN-LAST:event_jcbSeleccionItemStateChanged

    private void jcbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionActionPerformed
        
    }//GEN-LAST:event_jcbSeleccionActionPerformed

    private void jcbSeleccionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jcbSeleccionInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSeleccionInputMethodTextChanged

    private void jcbSeleccionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbSeleccionMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbSeleccionMouseReleased

    private void jcbSeleccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbSeleccionMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbSeleccionMousePressed

    private void jcbSeleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbSeleccionMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbSeleccionMouseEntered

    
    private void jbtnBuscarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarFotoActionPerformed
            JFileChooser j = new JFileChooser();
        j.setCurrentDirectory(new File("Imagenes/"));
        int ap = j.showOpenDialog(this);
        
        if(ap == JFileChooser.APPROVE_OPTION){
            ruta = j.getSelectedFile().getAbsolutePath();
            lblImagen.setIcon(new ImageIcon(ruta));
            lblruta.setText(ruta);
        }
    }//GEN-LAST:event_jbtnBuscarFotoActionPerformed
    
    //limpiar jtextfield
    public void limpiarJtext(){
        txtNombre.setText("");
        txtApellidos.setText("");
        txtEdad.setText("");
        txtCamisola.setText("");
        txtHabilidades.setText("");
        txtMarca.setText("");
        txtValorMercado.setText("");
    }
    
    //SELECCION DE TIPO DE JUGADR
    public void seleccionarTipo(){
        String sel = jcbTipo.getSelectedItem().toString();
        System.out.println(sel);
        //jcbTipo.removeAllItems();
        
        mostrarTipoJugadores();
        
        convertirTipo(sel);
        System.out.println(idTipo);
        lblposicion.setText(sel);
    }
    

    //SELECCION DE PLANTEL
    public void seleccionar(){
        String sel = jcbSeleccion.getSelectedItem().toString();
        System.out.println(sel);
        jcbSeleccion.removeAllItems();
        
        mostrarComboSelecciones();
        
        convertirSeleccion(sel);
        System.out.println(idSeleccion);
        lblSeleccion.setText(sel);
    }
    
    //METODO CONVERTIR ID DE SELECCION
    public void convertirSeleccion(String seleccion){
        
        String query = "SELECT id_seleccion, seleccion FROM `seleccion`\n" +
                    "WHERE seleccion = '"+seleccion+"';";
         try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query);
        
            while (rs.next()) {
                idSeleccion = rs.getInt("id_seleccion");
            }
            //System.out.println(idSeleccion);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    //convertir id tipo
    public void convertirTipo(String tipo){
        String query = "SELECT id_tipo, tipo from tipo_jugador WHERE tipo = '"+tipo+"';";
         try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query);
        
            while (rs.next()) {
                idTipo = rs.getInt("id_tipo");
            }
            //System.out.println(idTipo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    //Metodo guardar
    public void guardarJugador(String nombre, String apellidos, String img_foto, int edad, int camisola, String habilidad, String p_habil, String nacionalizado, int id_seleccion, int id_tipo, String marca, int valor){
        
        String sql_guardar;
        
        sql_guardar = "INSERT INTO jugador VALUES (NULL,'"
                + nombre + "', '"
                + apellidos + "', '"
                + img_foto +"', "
                + edad + ", "
                + camisola + ", '"
                + habilidad +"', '"
                + p_habil +"', '"
                + nacionalizado +"', "
                + id_seleccion + ", "
                + id_tipo + ", '"
                + marca +"', "
                + valor + ")";
                
                System.out.println(sql_guardar);
                
                try {
                con = cn.getConection();
                st = con.createStatement();
                st.execute(sql_guardar);
            
            JOptionPane.showMessageDialog(null, "Jugador Registrado exitosamente!!");
            
             
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, e);
        }
               
        
        
    }
    
    //Metodo mostrar selecciones en combobox
    public void mostrarComboSelecciones(){
        
        String query = "SELECT seleccion FROM seleccion";
        
         try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query);
            
             while (rs.next()) {
                 jcbSeleccion.addItem((String) rs.getObject("seleccion"));
             }
                       
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    //mostrar tipos de jugadores en combobox
    public void mostrarTipoJugadores(){
        String query = "SELECT id_tipo, tipo FROM tipo_jugador;";
        
         try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query);
            
             while (rs.next()) {
                 jcbTipo.addItem((String) rs.getObject("tipo"));
             }
                       
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJugadorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJugadorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJugadorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJugadorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJugadorUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBuscarFoto;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnGuardar1;
    private javax.swing.JComboBox<String> jcbNacionalizado;
    private javax.swing.JComboBox<String> jcbPierna;
    private javax.swing.JComboBox<String> jcbSeleccion;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblposicion;
    private javax.swing.JLabel lblruta;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCamisola;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtHabilidades;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValorMercado;
    // End of variables declaration//GEN-END:variables
}
