package formularios;

import clases.ConexionBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio Cabrera
 */
public class jpanelJugadores_vista extends javax.swing.JPanel {
    ConexionBD cn = new ConexionBD(); 
    DefaultTableModel modelo; // EL MODELO PARA PODER TRABAJAR CON EL JTABLE
    Connection con;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form jpanelJugadores
     */
    public jpanelJugadores_vista() {
        initComponents();
        
         mostrarComboSelecciones();
         
        
    }
    //global
    int id_encontrado = 0;
    
     //MOSTRAR REGISTROS
    public void mostrarDatos(int id){
       
        
        String query = "SELECT id_jugador, nombre, apellidos, tipo, seleccion\n" +
"FROM jugador\n" +
"INNER JOIN tipo_jugador\n" +
"on jugador.id_tipo = tipo_jugador.id_tipo\n" +
"INNER JOIN seleccion\n" +
"ON jugador.id_seleccion = seleccion.id_seleccion\n" +
"WHERE jugador.id_seleccion = "+id+"";
        System.out.println(query);
         try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query);
        
            Object[] usuarios = new Object[12];
            modelo = (DefaultTableModel) tablaUsuarios.getModel();
            while (rs.next()) {
                usuarios[0] = rs.getInt("id_jugador");
                usuarios[1] = rs.getString("nombre");
                usuarios[2] = rs.getString("apellidos");
                usuarios[3] = rs.getString("tipo");
                usuarios[4] = rs.getString("seleccion");
                
                modelo.addRow(usuarios);
            }
            tablaUsuarios.setModel(modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        

    }//fin metodo mostrar
    
    
    //mostrar datos en combobox
    public void mostrarComboSelecciones(){
        String query = "SELECT seleccion FROM seleccion;";
        
         try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query);
            
             while (rs.next()) {
                 jcbSelecciones.addItem((String) rs.getObject("seleccion"));
             }
                       
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    public int seleccionarIdSeleccion(){
        String selec_buscar;
        selec_buscar = jcbSelecciones.getSelectedItem().toString();
       
        String query2 = "SELECT id_pais FROM seleccion WHERE seleccion = '"+selec_buscar+"'";
        
        //System.out.println(selec_buscar);
        try {
            con = cn.getConection();
            st = con.createStatement();
            rs = st.executeQuery(query2);
           
            
            while (rs.next()) {
               id_encontrado = rs.getInt("id_pais");
               
            }
            //System.out.println(id_encontrado);
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return id_encontrado;
        
    }
    
     public void limpiarModelo(){
        for (int i = 0; i < tablaUsuarios.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }//fin metodo limpiartabla
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        lbl_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcbSelecciones = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbtnBuscar1 = new javax.swing.JButton();
        jtfJugador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista de jugadores");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Jugador", "Nombre", "Apellido", "Posición", "Selección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jcbSelecciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcbSelecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSeleccionesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Elija selección a mostrar:");

        jbtnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search-icon.png"))); // NOI18N
        jbtnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscar1ActionPerformed(evt);
            }
        });

        jtfJugador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfJugador.setPreferredSize(new java.awt.Dimension(100, 20));
        jtfJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJugadorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jugador seleccionado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbSelecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jcbSelecciones, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        int item = tablaUsuarios.getSelectedRow();
        
        lbl_id.setText(tablaUsuarios.getValueAt(item, 0).toString());
        jtfJugador.setText(tablaUsuarios.getValueAt(item, 1).toString()+" "+tablaUsuarios.getValueAt(item, 2).toString());

    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void jbtnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscar1ActionPerformed
        // TODO add your handling code here:
        limpiarModelo();
        seleccionarIdSeleccion();
        int id = id_encontrado;
        mostrarDatos(id_encontrado);
    }//GEN-LAST:event_jbtnBuscar1ActionPerformed

    private void jcbSeleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSeleccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSeleccionesActionPerformed

    private void jtfJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar1;
    private javax.swing.JComboBox<String> jcbSelecciones;
    private javax.swing.JTextField jtfJugador;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
